import numpy as np
ar1=np.array([[1,2],[3,4]])
ar2=np.array([[5,6],[7,8]])
print("Add two matrices")
print(np.add(ar1,ar2))
print("substract two matrices")
print(np.subtract(ar1,ar2))
print("multiple individuals elements of the matrix")
print(np.multiply(ar1,ar2))
print("divide the element of the matrix")
print(np.divide(ar1,ar2))
print("perform matrix multiplication")
print(np.dot(ar1,ar2))
print("Display the transpose of the matrix")
print(ar1.transpose())
print(ar2.transpose())
print("sum of diogonal elements of the matrix")
print(np.trace(ar1))
print(np.trace(ar2))

